# Test configuration for Metasrv with etcd backend (GreptimeDB format)
data_home = "./test_data/metasrv"
store_addrs = ["127.0.0.1:2379"]
store_key_prefix = "/greptime_test"
backend = "etcd_store"

# gRPC server configuration
[grpc]
addr = "127.0.0.1:3002"
runtime_size = 8

# HTTP server configuration  
[http]
addr = "127.0.0.1:4001"
timeout = "30s"
