# GreptimeDB Datanode Test Configuration
# This configuration is designed for testing datanode connectivity and functionality

# Node configuration
node_id = 0
require_lease_before_startup = false
init_regions_in_background = false
enable_telemetry = true

# HTTP server configuration
[http]
addr = "127.0.0.1:5000"
timeout = "30s"
body_limit = "64MB"

# gRPC server configuration
[grpc]
bind_addr = "127.0.0.1:3001"
server_addr = "127.0.0.1:3001"
runtime_size = 8
max_recv_message_size = "512MB"
max_send_message_size = "512MB"

[grpc.tls]
mode = "disable"

# Heartbeat configuration
[heartbeat]
interval = "3s"
retry_interval = "3s"

# Metasrv client configuration
[meta_client]
metasrv_addrs = ["127.0.0.1:3002"]
timeout = "3s"
heartbeat_timeout = "500ms"
ddl_timeout = "10s"
connect_timeout = "1s"
tcp_nodelay = true

# WAL configuration
[wal]
provider = "raft_engine"
dir = "./test_data/datanode/wal"
file_size = "128MB"
purge_threshold = "1GB"

# Query engine configuration
[query]
parallelism = 0

# Storage configuration - MinIO S3 storage (comprehensive performance testing)
[storage]
data_home = "./test_data/datanode"
type = "S3"
bucket = "greptime-test-bucket"
root = "test-data"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
endpoint = "http://localhost:9000"
region = "us-east-1"

# Local cache configuration for S3
cache_path = "./test_data/datanode/cache"
cache_capacity = "1GiB"

# Region engine configuration
[[region_engine]]
[region_engine.mito]
worker_channel_size = 128
worker_request_batch_size = 64
auto_flush_interval = "1h"
sst_write_buffer_size = "8MB"

# Index configuration
[region_engine.mito.index]
aux_path = "./test_data/datanode/index_intermediate"

# Memtable configuration
[region_engine.mito.memtable]
type = "time_series"

# Enable file engine
[[region_engine]]
[region_engine.file]

# Enable metric engine
[[region_engine]]
[region_engine.metric]

# Logging configuration
[logging]
dir = "./test_data/logs/datanode"
level = "info"
append_stdout = true
log_format = "text"
