# Example Datanode configuration with file storage

node_id = 1
metasrv_addrs = ["127.0.0.1:3002"]

[meta_client]
metasrv_addrs = ["127.0.0.1:3002"]

[storage]
storage_type = "File"
root = "/tmp/greptimedb/data"

[server]
addr = "127.0.0.1:3001"
http_addr = "127.0.0.1:14100"
grpc_addr = "127.0.0.1:14101"
