# Example Datanode configuration with S3 storage

metasrv_addrs = ["127.0.0.1:3002"]

[storage]
storage_type = "S3"
bucket = "test-bucket"
root = "data/"
access_key_id = "minioadmin"
secret_access_key = "minioadmin123"
endpoint = "http://127.0.0.1:9000"
region = "us-east-1"

[server]
addr = "0.0.0.0:4100"
http_addr = "0.0.0.0:4101"
grpc_addr = "0.0.0.0:4102"
