# Example Frontend configuration

metasrv_addrs = ["127.0.0.1:3002"]

[meta_client]
metasrv_addrs = ["127.0.0.1:3002"]

[server]
addr = "127.0.0.1:4000"
http_addr = "127.0.0.1:14200"
grpc_addr = "127.0.0.1:14201"
