# Example Metasrv configuration with etcd store

[store]
store_type = "etcd_store"
store_addrs = ["127.0.0.1:2379"]
store_key_prefix = "/greptime"
max_txn_ops = 128

[server]
addr = "0.0.0.0:3002"

[http]
addr = "127.0.0.1:14001"
